### ISSUE TITLE
Unhandled JSON root objects: number,  string,  true,  false, null

### ISSUE THREAD

**Issue by rutsky** [Lapple/react-json-inspector#14]
JSON specification allows to represent `number` and `string` types objects, `true`, `false` and `null` values as root object, which isn't supported in react-json-inspector.

E.g. following code fails:

```
<JsonInspector data={null} />
```

Following code displays `Nothing found`:

```
<JsonInspector data={123} />
```

**Comment by Lapple** [comment]
This is something that has completely fallen out of my sight, will fix for sure, thanks!
