### ISSUE TITLE
Usable without a JSX compiler

### ISSUE THREAD

**Issue by lostpebble** [Lapple/react-json-inspector#2]
I really like using this to quickly show JSON data while I'm prototyping, but the biggest drawback for me is when I'm using Webpack and all my scripts are transpiled into ES5 javascript but this component is still using JSX in its code I get an error.

I exclude my loaders from parsing the /node_modules folder (a recommended practice with Webpack), but to use this component I have to include your component folder specifically in my loaders.

I feel like this module, and all node modules for that matter, should be transpiled by default into ES5 javascript for compatibility and ease of use.

**Comment by Lapple** [comment]
Thank you, I wanted to remove dependency on JSX anyway, mostly because it changes rapidly now. The update is published on npm under `4.2.1`, please take a look and tell me if it works for you.

**Comment by lostpebble** [comment]
Thanks, it's working without the extra loader now.
