### ISSUE TITLE
update npm version

### ISSUE THREAD

**Issue by barbalex** [Lapple/react-json-inspector#20]
please update to v6
v5.4 is not compatible with react 14

**Comment by Lapple** [comment]
you could be getting older version because of this: https://github.com/Lapple/react-json-inspector/issues/19#issuecomment-154371184, does this apply?

**Comment by barbalex** [comment]
according to this: https://www.npmjs.com/package/react-json-inspector
npm-version is still 5.4

**Comment by Lapple** [comment]
That's because I mistakenly published 5.4 after 6.0. Planning to fix this once any patch for 6.0 is ready.

**Comment by barbalex** [comment]
Thanks

That explains why `npm-check-updates` does not detect v6.

I am having BIG trouble running `npm install` on my windows machine now, so I can't test installing v6 manually but I guess it should work.

**Comment by barbalex** [comment]
yep, updating by setting the version to 6.0.0 in package.json works
thanks for this great tool!
