### ISSUE TITLE
Publish version 6.0.0 to npm

### ISSUE THREAD

**Issue by AoDev** [Lapple/react-json-inspector#23]
Hello, your last version is not published on npm. (5.4.0 is latest there)

This prevents from using it with react 0.14.x

**Comment by Lapple** [comment]
Hi, 6.1.0 was published just now, could you give it a try?

**Comment by AoDev** [comment]
@Lapple Thanks, I just installed it and it is working. (I haven't checked everything, only that it runs)

Thank you
