### ISSUE TITLE
npm WARN react-json-inspector@7.1.1 requires a peer of react@^15.0.0 but none is installed

### ISSUE THREAD

**Issue by broofa** [Lapple/react-json-inspector#42]
It'd be nice to be able use this with `react >= 16` without getting this warning.

(FWIW, I'm using with react 16.8 and it seems to be behaving)

**Comment by austinnichols101** [comment]
No commits to this project since Nov. 2017.  

@Lapple - is this project still alive?

**Comment by broofa** [comment]
... ping?

![image](https://user-images.githubusercontent.com/164050/59453098-00eab900-8dc4-11e9-867f-c5e67747e118.png)

**Comment by raptoria** [comment]
+1

**Comment by raptoria** [comment]
I created a PR to fix this issue: https://github.com/Lapple/react-json-inspector/pull/45

**Comment by broofa** [comment]
Two years, no comment from owner...

![image](https://media3.giphy.com/media/XsD8ammoDZwXK/giphy.gif)
