### ISSUE TITLE
Expansion state should not collapse everytime props are updated

### ISSUE THREAD

**Issue by ntucker** [Lapple/react-json-inspector#7]
A normal thing in react, is to have users enter data and instantly update state across the app. I am using this to monitor this behavior. However, everytime I enter anything, the entire table collapses making it impossible to track changes in realtime.

**Comment by Lapple** [comment]
Thank you, there was an unnecessary reset that I noticed recently, now it's gone. Fix is released as 5.1.0.

**Comment by ntucker** [comment]
Thanks! :)
